liip_imagine:
    driver: "gd"
    twig:
        mode: lazy
    filter_sets:
        miniature:
            quality: 95
            filters:
                thumbnail:
                    size: [480, 360]
                    mode: outbound
        logo:
            quality: 95