services:
  php:
    build:
      context: ./docker/php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - symfony_var:/var/www/html/var
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      MAILER_DSN: "smtp://alexandre@bourlier.email:S%2Au680M%3FA.1V@melon.o2switch.net:465"
      DATABASE_URL: "mysql://boal2619:D%2CqWM%7DzgpC8_6wfK%5D%25@mysql:3306/boal2619_portfolio?serverVersion=8.4&charset=utf8mb4"
    depends_on:
      - mysql
      - mailpit
    networks:
      - app

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - symfony_var:/var/www/html/var:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - app

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: boal2619_portfolio
      MYSQL_USER: boal2619
      MYSQL_PASSWORD: "D,qWM}zgpC8_6wfK]%"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      app:
        aliases:
          - mysql

  phpmyadmin:
    image: phpmyadmin:5
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
    restart: unless-stopped
    networks:
      - app

volumes:
  mysql_data:
  symfony_var:

networks:
  app:
    driver: bridge